Repository sassoftware/viya4-iac-gcp, pull requests merged in 2021-05, with the labels that each got.

#86 #85 clarify BYO subnet variable syntax
  docs/CONFIG-VARS.md
  examples/sample-input-byo.tfvars
Labels: bug, documentation

#88 #87 align types in network module output
  modules/network/outputs.tf
Labels: bug

#90 Updated Jump/NFS Server OS to 20.04 resolving google-guest-agent issue
  modules/google_vm/variables.tf
  vm.tf
Labels: bug

#91 network outputs for auto / byo now fixed
  modules/network/outputs.tf
Labels: bug

#94 Fixed subnet output issues
  modules/network/outputs.tf
Labels: bug

#95 Updated diagram
  docs/images/viya4-iac-gcp-diag.png
Labels: documentation
