Repository sassoftware/viya4-iac-gcp, pull requests merged in 2022-10, with the labels that each got.

#142 feat: (IAC-476) Update Providers, Modules, & Dependencies
  README.md
  locals.tf
  main.tf
  modules/google_vm/main.tf
  modules/network/variables.tf
  network.tf
  variables.tf
  versions.tf
Labels: enhancement

#147 fix: (IAC-476) Change Filestore location param value
  main.tf
Labels: bug

#149 4.0.0 - October 20, 2022
  README.md
  docs/CONFIG-VARS.md
  locals.tf
  main.tf
  modules/google_vm/main.tf
  modules/network/variables.tf
  network.tf
  variables.tf
  versions.tf
Labels: bug, documentation, enhancement
