Repository sassoftware/viya4-iac-gcp, pull requests merged in 2023-06, with the labels that each got.

#178 feat: (IAC-895) Add Support to Toggle the Google Cloud Managed Service for Prometheus
  docs/CONFIG-VARS.md
  main.tf
  variables.tf
Labels: documentation, enhancement

#184 5.1.0 - June 15, 2023
  Dockerfile
  docs/CONFIG-VARS.md
  main.tf
  variables.tf
Labels: documentation, enhancement

#183 feat: (IAC-1065) Add Hadolint, ShellCheck and TFLint Checks via GitHub Actions
  .github/workflows/linter-analysis.yaml
  Dockerfile
  docker-entrypoint.sh
  linting-configs/.hadolint.yaml
  linting-configs/.shellcheckrc
  linting-configs/.tflint.hcl
  locals.tf
  main.tf
  modules/google_vm/outputs.tf
  modules/google_vm/variables.tf
  modules/kubeconfig/locals.tf
  modules/network/main.tf
  modules/network/outputs.tf
  modules/network/variables.tf
  network.tf
  outputs.tf
  variables.tf
  vms.tf
Labels: enhancement

#181 docs: (IAC-1006) GKE - Update IAC CDS Postgres CONFIG VARS documentation
  docs/CONFIG-VARS.md
Labels: documentation

#186 5.2.0 - June 26, 2023
  .github/workflows/linter-analysis.yaml
  Dockerfile
  docker-entrypoint.sh
  linting-configs/.hadolint.yaml
  linting-configs/.shellcheckrc
  linting-configs/.tflint.hcl
  locals.tf
  main.tf
  modules/google_vm/outputs.tf
  modules/google_vm/variables.tf
  modules/kubeconfig/locals.tf
  modules/network/main.tf
  modules/network/outputs.tf
  modules/network/variables.tf
  network.tf
  outputs.tf
  variables.tf
  vms.tf
Labels: documentation, enhancement
