Repository sassoftware/viya4-iac-gcp, pull requests merged in 2025-06, with the labels that each got.

#265 feat: initial testing framework (PSKD-1682)
  .github/workflows/default-plan-unit-tests.yml
  .gitignore
  CONTRIBUTING.md
  Dockerfile.terratest
  docs/user/TerratestDockerUsage.md
  docs/user/TestingPhilosophy.md
  test/create_credentials_file.go
  test/defaultapply/default_apply_main_test.go
  test/defaultplan/defaults_test.go
  test/go.mod
  test/go.sum
  test/helpers/apply_helper.go
  test/helpers/apply_retrievers.go
  test/helpers/apply_test_case.go
  test/helpers/helper_test.go
  test/helpers/json_path.go
  test/helpers/plan_cache.go
  test/helpers/test_case.go
  test/helpers/validation.go
  test/terratest_docker_entrypoint.sh
  test/testoutput/parse_results.go
Labels: enhancement

#274 chore(gcp): Add the community features READMEs
  docs/community/README.md
  docs/community/community-config-vars.md
Labels: chore

#280 fix: update VMs to use Ubuntu 24.04
  .github/release-drafter.yml
  .github/workflows/conventional-commits.yml
  modules/google_vm/main.tf
  modules/google_vm/variables.tf
  test/helpers/helper_test.go
  vms.tf
Labels: bug
